services:

  mongodb:
    image: mongo:latest
    container_name: mevn_mongodb
    restart: unless-stopped
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: Admin1234!
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: